### ISSUE TITLE
Open to patches?

### ISSUE THREAD

**Issue by panaflexx** [Akadeax/cpp-gng#1]
Really enjoyed your code! I wrote some patches that improves the gameplay - ladders now work and gravestones work.  I added some basic events also. Are you interested?  Would you be open to adding a license?  Thanks!

**Comment by Akadeax** [comment]
Added a license for your convenience. I would be very interested in seeing your patches! This is an exam project for University, but absolutely feel free to fork this repository. I genuinely appreciate the interest.

**Comment by panaflexx** [comment]
Cool! I'm happy to share.  I added a PR, you can check out my repo from there and merge as you like.  I am on Linux, so I added a CMake option also.
